* =org-roam.nvim=
  #+BEGIN_QUOTE
    This project is no longer maintained. Why? Read
  [[https://github.com/nvim-orgmode/orgmode/issues/66#issuecomment-1702631466][this]]
  #+END_QUOTE

  This plugin tries to have one to one feature parity with the original [[https://github.com/org-roam/org-roam][org-roam]]

  If you are new to this checkout the org-roam [[https://www.orgroam.com/manual.html][manual]]

** Installation with packer
   #+BEGIN_SRC lua
     use({
         "SyedFasiuddin/org-roam.nvim",
         config = function ()
             local org_roam = require("org-roam")
             org_roam.setup({
                 -- required
                 org_roam_directory = "~/OrgRoam",

                 -- required (not checked if present)
                 org_roam_database_file = "~/.config/emacs/org-roam.db"
             })

             vim.keymap.set("n", "<Leader>nf", org_roam.org_roam_node_find)
             vim.keymap.set("n", "<Leader>nc", org_roam.org_roam_capture)
         end,
         requires = { "kkharji/sqlite.lua" }
     })
   #+END_SRC

* Installation with lazy.nvim
  #+BEGIN_SRC lua
    {
        "SyedFasiuddin/org-roam.nvim",
        dependencies = { "kkharji/sqlite.lua" },
        opts = {
            -- required
            org_roam_directory = "~/OrgRoam",
            -- required (not checked if present)
            org_roam_database_file = "~/.config/emacs/org-roam.db"
        },
        keys = {
            {
                "<Leader>nf",
                "<Cmd>lua require(\"org-roam\").org_roam_node_find()<CR>",
            },
            {
                "<Leader>nc",
                "<Cmd>lua require(\"org-roam\").org_roam_capture()<CR>",
            },
        },
    }
  #+END_SRC

** What features are supported?
   - Find node: =org_roam_node_find=
   - Capture node: =org_roam_capture=

** TODO If ~/OrgRoam folder not found, create one
** TODO Performance issue
   I read a single file, again and again, if the file is large, it may be a problem,
   currently, I focus on logic only, performance will be the next one to be 
   tackled
** TODO refactor
** TODO add test case
** TODO completion
** TODO Heading backlink, currently only works for file
** TODO Network graph view
   Seems hard to do in Neovim itself? Since the basic render unit is a box cell.
   Maybe you can count on an external program, like just open a new emacs window
   for this purpose. Can I just like org-roam-ui, using browser and websocket to
   do it?
   - [[https://cmdln.org/2023/03/25/how-i-org-in-2023/][org-roam-ui]]
** TODO Maybe consider status bar to show how many backlink does current file have?

** What features are not supported yet?


** Related links
   - [[https://wohanley.com/posts/org-setup/][My current org-mode setup]]
   - [[https://systemcrafters.net/build-a-second-brain-in-emacs/capturing-notes-efficiently/][Capturing Notes Efficiently with Org Roam]]
   - [[https://github.com/org-roam/org-roam-ui][Graph visualization]]
   - [[https://github.com/kkharji/sqlite.lua][SQLite lua]]
